### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by ubnt-intrepid** [ubnt-intrepid/mison-rs#1]
### Index Builder
- [x] Step 1 (`build_strucural_character_bitmaps`, d8aeb78)
- [x] Step 2 (`remove_unstructural_quotes`, 95c18ce)
- [x] Step 3 (`build_string_mask_bitmap`, f54183f)
- [x] Step 4 (`build_leveled_colon_bitmap`, 172ad14)

### Basic parsing
- [x] define `Value`
- [x] add `Parser`

### Query Parsing
- [x] add `QueryTree` and `QueryNode` (cd8be33)
- [x] add `QueryParser`

### Speculative Parsing
- [x] define pattern tree
- [x] implemement training phase
- [x] implement speculative parser

### Misc
- [ ] add support for array field in `QueryTree`
- [ ] fuzzing
- [ ] validatation of escaped strings (in `EscapedStr`)
